# This workflow will test DULHAN-MD on every push

name: DULHAN-MD CI Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check if bot can start (run for 20 seconds)
        run: |
          echo "Starting bot for a quick health check..."
          # Start the bot, wait 20 seconds, then kill the process.
          # The "|| true" part ensures the workflow doesn't fail due to the timeout command's exit code.
          timeout 20s npm start || true
          echo "Health check finished. If no crash occurred, the code is likely okay."
